apiVersion: v1
kind: ServiceAccount
metadata:
  name: wipp-backend-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: wipp-backend-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "patch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "watch"]
  - apiGroups: ["argoproj.io"]
    resources: ["workflows"]
    verbs: ["delete", "deletecollection", "get", "list", "patch", "create", "update", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wipp-backend-rb
subjects:
  - kind: ServiceAccount
    name: wipp-backend-sa
roleRef:
  kind: Role
  name: wipp-backend-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wipp-backend
spec:
  selector:
    matchLabels:
      app: wipp-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: wipp-backend
    spec:
      serviceAccountName: wipp-backend-sa
      containers:
        - image: labshare/wipp-backend:BACKEND_VERSION_VALUE
          name: wipp-backend
          imagePullPolicy: Always
          args: ["wipp-mongo", "27017", "WIPP_PVC_NAME_VALUE"]
          env:
            - name: ELASTIC_APM_SERVER_URLS
              value: ELASTIC_APM_URL_VALUE
            - name: ELASTIC_APM_SERVICE_NAME
              value: wipp-backend
            - name: ELASTIC_APM_APPLICATION_PACKAGES
              value: gov.nist.itl.ssd.wipp.backend
            - name: NODE_SELECTOR
              value: NODE_SELECTOR_VALUE
            - name: TOLERATIONS
              value: TOLERATIONS_VALUE
            - name: OME_CONVERTER_THREADS
              value: OME_CONVERTER_THREADS_VALUE
            - name: KEYCLOAK_AUTH_URL
              value: KEYCLOAK_AUTH_URL_VALUE
            - name: WORKFLOW_PLUGINHARDWAREREQUIREMENTS_ENABLED
              value: WORKFLOW_PLUGINHARDWAREREQUIREMENTS_ENABLED_VALUE
          volumeMounts:
            - mountPath: /data/WIPP-plugins
              name: data
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 2
            requests:
              cpu: 1
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: WIPP_PVC_NAME_VALUE
      restartPolicy: Always
